; Proxy shell trampolines (#83, ml64) - GENERATED by scripts/gen_shell_asm.py.
; Export table source: link /dump /exports System32\xinput1_4.dll (via
; src/shell/shell_exports.h, SHELL_ID=3). Ordinals are the REAL dll's
; ordinals - games import by ordinal via the .lib (d3d12.lib maps
; D3D12CreateDevice to ordinal 101), so the table must match exactly.
; Each slot: save volatile arg registers -> first entry calls ProxyBootstrap
; (guarded by g_inited; steady state is cmp+jne only) -> restore -> jmp to
; the real dll's same slot (by name; unnamed slots by ordinal). Signature-
; agnostic: stack args stay in place, register args are saved/restored.
option casemap:none

extern g_procs:qword
extern g_inited:byte
extern ProxyBootstrap:proc

.code

JUMP MACRO idx
    sub     rsp, 104
    movaps  [rsp+0], xmm3
    mov     [rsp+16], rcx
    mov     [rsp+24], rdx
    mov     [rsp+32], r8
    mov     [rsp+40], r9
    movaps  [rsp+48], xmm0
    movaps  [rsp+64], xmm1
    movaps  [rsp+80], xmm2
    cmp     byte ptr [g_inited], 0
    jne     SHORT skip_init&idx&
    call    ProxyBootstrap
skip_init&idx&:
    movaps  xmm3, [rsp+0]
    mov     rcx, [rsp+16]
    mov     rdx, [rsp+24]
    mov     r8,  [rsp+32]
    mov     r9,  [rsp+40]
    movaps  xmm0, [rsp+48]
    movaps  xmm1, [rsp+64]
    movaps  xmm2, [rsp+80]
    add     rsp, 104
    jmp     qword ptr [g_procs+idx*8]
ENDM

OrdinalSlot_1                                              PROC
    JUMP 0
OrdinalSlot_1                                              ENDP
XInputGetState                                             PROC
    JUMP 1
XInputGetState                                             ENDP
XInputSetState                                             PROC
    JUMP 2
XInputSetState                                             ENDP
XInputGetCapabilities                                      PROC
    JUMP 3
XInputGetCapabilities                                      ENDP
XInputEnable                                               PROC
    JUMP 4
XInputEnable                                               ENDP
OrdinalSlot_6                                              PROC
    JUMP 5
OrdinalSlot_6                                              ENDP
XInputGetBatteryInformation                                PROC
    JUMP 6
XInputGetBatteryInformation                                ENDP
XInputGetKeystroke                                         PROC
    JUMP 7
XInputGetKeystroke                                         ENDP
OrdinalSlot_9                                              PROC
    JUMP 8
OrdinalSlot_9                                              ENDP
XInputGetAudioDeviceIds                                    PROC
    JUMP 9
XInputGetAudioDeviceIds                                    ENDP
OrdinalSlot_11                                             PROC
    JUMP 10
OrdinalSlot_11                                             ENDP
OrdinalSlot_12                                             PROC
    JUMP 11
OrdinalSlot_12                                             ENDP
OrdinalSlot_13                                             PROC
    JUMP 12
OrdinalSlot_13                                             ENDP
OrdinalSlot_14                                             PROC
    JUMP 13
OrdinalSlot_14                                             ENDP
OrdinalSlot_15                                             PROC
    JUMP 14
OrdinalSlot_15                                             ENDP
OrdinalSlot_16                                             PROC
    JUMP 15
OrdinalSlot_16                                             ENDP
OrdinalSlot_17                                             PROC
    JUMP 16
OrdinalSlot_17                                             ENDP
OrdinalSlot_18                                             PROC
    JUMP 17
OrdinalSlot_18                                             ENDP
OrdinalSlot_19                                             PROC
    JUMP 18
OrdinalSlot_19                                             ENDP
OrdinalSlot_20                                             PROC
    JUMP 19
OrdinalSlot_20                                             ENDP
OrdinalSlot_21                                             PROC
    JUMP 20
OrdinalSlot_21                                             ENDP
OrdinalSlot_22                                             PROC
    JUMP 21
OrdinalSlot_22                                             ENDP
OrdinalSlot_23                                             PROC
    JUMP 22
OrdinalSlot_23                                             ENDP
OrdinalSlot_24                                             PROC
    JUMP 23
OrdinalSlot_24                                             ENDP
OrdinalSlot_25                                             PROC
    JUMP 24
OrdinalSlot_25                                             ENDP
OrdinalSlot_26                                             PROC
    JUMP 25
OrdinalSlot_26                                             ENDP
OrdinalSlot_27                                             PROC
    JUMP 26
OrdinalSlot_27                                             ENDP
OrdinalSlot_28                                             PROC
    JUMP 27
OrdinalSlot_28                                             ENDP
OrdinalSlot_29                                             PROC
    JUMP 28
OrdinalSlot_29                                             ENDP
OrdinalSlot_30                                             PROC
    JUMP 29
OrdinalSlot_30                                             ENDP
OrdinalSlot_31                                             PROC
    JUMP 30
OrdinalSlot_31                                             ENDP
OrdinalSlot_32                                             PROC
    JUMP 31
OrdinalSlot_32                                             ENDP
OrdinalSlot_33                                             PROC
    JUMP 32
OrdinalSlot_33                                             ENDP
OrdinalSlot_34                                             PROC
    JUMP 33
OrdinalSlot_34                                             ENDP
OrdinalSlot_35                                             PROC
    JUMP 34
OrdinalSlot_35                                             ENDP
OrdinalSlot_36                                             PROC
    JUMP 35
OrdinalSlot_36                                             ENDP
OrdinalSlot_37                                             PROC
    JUMP 36
OrdinalSlot_37                                             ENDP
OrdinalSlot_38                                             PROC
    JUMP 37
OrdinalSlot_38                                             ENDP
OrdinalSlot_39                                             PROC
    JUMP 38
OrdinalSlot_39                                             ENDP
OrdinalSlot_40                                             PROC
    JUMP 39
OrdinalSlot_40                                             ENDP
OrdinalSlot_41                                             PROC
    JUMP 40
OrdinalSlot_41                                             ENDP
OrdinalSlot_42                                             PROC
    JUMP 41
OrdinalSlot_42                                             ENDP
OrdinalSlot_43                                             PROC
    JUMP 42
OrdinalSlot_43                                             ENDP
OrdinalSlot_44                                             PROC
    JUMP 43
OrdinalSlot_44                                             ENDP
OrdinalSlot_45                                             PROC
    JUMP 44
OrdinalSlot_45                                             ENDP
OrdinalSlot_46                                             PROC
    JUMP 45
OrdinalSlot_46                                             ENDP
OrdinalSlot_47                                             PROC
    JUMP 46
OrdinalSlot_47                                             ENDP
OrdinalSlot_48                                             PROC
    JUMP 47
OrdinalSlot_48                                             ENDP
OrdinalSlot_49                                             PROC
    JUMP 48
OrdinalSlot_49                                             ENDP
OrdinalSlot_50                                             PROC
    JUMP 49
OrdinalSlot_50                                             ENDP
OrdinalSlot_51                                             PROC
    JUMP 50
OrdinalSlot_51                                             ENDP
OrdinalSlot_52                                             PROC
    JUMP 51
OrdinalSlot_52                                             ENDP
OrdinalSlot_53                                             PROC
    JUMP 52
OrdinalSlot_53                                             ENDP
OrdinalSlot_54                                             PROC
    JUMP 53
OrdinalSlot_54                                             ENDP
OrdinalSlot_55                                             PROC
    JUMP 54
OrdinalSlot_55                                             ENDP
OrdinalSlot_56                                             PROC
    JUMP 55
OrdinalSlot_56                                             ENDP
OrdinalSlot_57                                             PROC
    JUMP 56
OrdinalSlot_57                                             ENDP
OrdinalSlot_58                                             PROC
    JUMP 57
OrdinalSlot_58                                             ENDP
OrdinalSlot_59                                             PROC
    JUMP 58
OrdinalSlot_59                                             ENDP
OrdinalSlot_60                                             PROC
    JUMP 59
OrdinalSlot_60                                             ENDP
OrdinalSlot_61                                             PROC
    JUMP 60
OrdinalSlot_61                                             ENDP
OrdinalSlot_62                                             PROC
    JUMP 61
OrdinalSlot_62                                             ENDP
OrdinalSlot_63                                             PROC
    JUMP 62
OrdinalSlot_63                                             ENDP
OrdinalSlot_64                                             PROC
    JUMP 63
OrdinalSlot_64                                             ENDP
OrdinalSlot_65                                             PROC
    JUMP 64
OrdinalSlot_65                                             ENDP
OrdinalSlot_66                                             PROC
    JUMP 65
OrdinalSlot_66                                             ENDP
OrdinalSlot_67                                             PROC
    JUMP 66
OrdinalSlot_67                                             ENDP
OrdinalSlot_68                                             PROC
    JUMP 67
OrdinalSlot_68                                             ENDP
OrdinalSlot_69                                             PROC
    JUMP 68
OrdinalSlot_69                                             ENDP
OrdinalSlot_70                                             PROC
    JUMP 69
OrdinalSlot_70                                             ENDP
OrdinalSlot_71                                             PROC
    JUMP 70
OrdinalSlot_71                                             ENDP
OrdinalSlot_72                                             PROC
    JUMP 71
OrdinalSlot_72                                             ENDP
OrdinalSlot_73                                             PROC
    JUMP 72
OrdinalSlot_73                                             ENDP
OrdinalSlot_74                                             PROC
    JUMP 73
OrdinalSlot_74                                             ENDP
OrdinalSlot_75                                             PROC
    JUMP 74
OrdinalSlot_75                                             ENDP
OrdinalSlot_76                                             PROC
    JUMP 75
OrdinalSlot_76                                             ENDP
OrdinalSlot_77                                             PROC
    JUMP 76
OrdinalSlot_77                                             ENDP
OrdinalSlot_78                                             PROC
    JUMP 77
OrdinalSlot_78                                             ENDP
OrdinalSlot_79                                             PROC
    JUMP 78
OrdinalSlot_79                                             ENDP
OrdinalSlot_80                                             PROC
    JUMP 79
OrdinalSlot_80                                             ENDP
OrdinalSlot_81                                             PROC
    JUMP 80
OrdinalSlot_81                                             ENDP
OrdinalSlot_82                                             PROC
    JUMP 81
OrdinalSlot_82                                             ENDP
OrdinalSlot_83                                             PROC
    JUMP 82
OrdinalSlot_83                                             ENDP
OrdinalSlot_84                                             PROC
    JUMP 83
OrdinalSlot_84                                             ENDP
OrdinalSlot_85                                             PROC
    JUMP 84
OrdinalSlot_85                                             ENDP
OrdinalSlot_86                                             PROC
    JUMP 85
OrdinalSlot_86                                             ENDP
OrdinalSlot_87                                             PROC
    JUMP 86
OrdinalSlot_87                                             ENDP
OrdinalSlot_88                                             PROC
    JUMP 87
OrdinalSlot_88                                             ENDP
OrdinalSlot_89                                             PROC
    JUMP 88
OrdinalSlot_89                                             ENDP
OrdinalSlot_90                                             PROC
    JUMP 89
OrdinalSlot_90                                             ENDP
OrdinalSlot_91                                             PROC
    JUMP 90
OrdinalSlot_91                                             ENDP
OrdinalSlot_92                                             PROC
    JUMP 91
OrdinalSlot_92                                             ENDP
OrdinalSlot_93                                             PROC
    JUMP 92
OrdinalSlot_93                                             ENDP
OrdinalSlot_94                                             PROC
    JUMP 93
OrdinalSlot_94                                             ENDP
OrdinalSlot_95                                             PROC
    JUMP 94
OrdinalSlot_95                                             ENDP
OrdinalSlot_96                                             PROC
    JUMP 95
OrdinalSlot_96                                             ENDP
OrdinalSlot_97                                             PROC
    JUMP 96
OrdinalSlot_97                                             ENDP
OrdinalSlot_98                                             PROC
    JUMP 97
OrdinalSlot_98                                             ENDP
OrdinalSlot_99                                             PROC
    JUMP 98
OrdinalSlot_99                                             ENDP
OrdinalSlot_100                                            PROC
    JUMP 99
OrdinalSlot_100                                            ENDP
OrdinalSlot_101                                            PROC
    JUMP 100
OrdinalSlot_101                                            ENDP
OrdinalSlot_102                                            PROC
    JUMP 101
OrdinalSlot_102                                            ENDP
OrdinalSlot_103                                            PROC
    JUMP 102
OrdinalSlot_103                                            ENDP
OrdinalSlot_104                                            PROC
    JUMP 103
OrdinalSlot_104                                            ENDP
OrdinalSlot_105                                            PROC
    JUMP 104
OrdinalSlot_105                                            ENDP
OrdinalSlot_106                                            PROC
    JUMP 105
OrdinalSlot_106                                            ENDP
OrdinalSlot_107                                            PROC
    JUMP 106
OrdinalSlot_107                                            ENDP
OrdinalSlot_108                                            PROC
    JUMP 107
OrdinalSlot_108                                            ENDP
END
