; Proxy shell trampolines (#83, ml64) - GENERATED by scripts/gen_shell_asm.py.
; Export table source: link /dump /exports System32\d3d11.dll (via
; src/shell/shell_exports.h, SHELL_ID=2). Ordinals are the REAL dll's
; ordinals - games import by ordinal via the .lib (d3d12.lib maps
; D3D12CreateDevice to ordinal 101), so the table must match exactly.
; Each slot: save volatile arg registers -> first entry calls ProxyBootstrap
; (guarded by g_inited; steady state is cmp+jne only) -> restore -> jmp to
; the real dll's same slot (by name; unnamed slots by ordinal). Signature-
; agnostic: stack args stay in place, register args are saved/restored.
option casemap:none

extern g_procs:qword
extern g_inited:byte
extern ProxyBootstrap:proc

.code

JUMP MACRO idx
    sub     rsp, 104
    movaps  [rsp+0], xmm3
    mov     [rsp+16], rcx
    mov     [rsp+24], rdx
    mov     [rsp+32], r8
    mov     [rsp+40], r9
    movaps  [rsp+48], xmm0
    movaps  [rsp+64], xmm1
    movaps  [rsp+80], xmm2
    cmp     byte ptr [g_inited], 0
    jne     SHORT skip_init&idx&
    call    ProxyBootstrap
skip_init&idx&:
    movaps  xmm3, [rsp+0]
    mov     rcx, [rsp+16]
    mov     rdx, [rsp+24]
    mov     r8,  [rsp+32]
    mov     r9,  [rsp+40]
    movaps  xmm0, [rsp+48]
    movaps  xmm1, [rsp+64]
    movaps  xmm2, [rsp+80]
    add     rsp, 104
    jmp     qword ptr [g_procs+idx*8]
ENDM

D3D11CreateDeviceForD3D12                                  PROC
    JUMP 0
D3D11CreateDeviceForD3D12                                  ENDP
D3DKMTCloseAdapter                                         PROC
    JUMP 1
D3DKMTCloseAdapter                                         ENDP
D3DKMTDestroyAllocation                                    PROC
    JUMP 2
D3DKMTDestroyAllocation                                    ENDP
D3DKMTDestroyContext                                       PROC
    JUMP 3
D3DKMTDestroyContext                                       ENDP
D3DKMTDestroyDevice                                        PROC
    JUMP 4
D3DKMTDestroyDevice                                        ENDP
D3DKMTDestroySynchronizationObject                         PROC
    JUMP 5
D3DKMTDestroySynchronizationObject                         ENDP
D3DKMTPresent                                              PROC
    JUMP 6
D3DKMTPresent                                              ENDP
D3DKMTQueryAdapterInfo                                     PROC
    JUMP 7
D3DKMTQueryAdapterInfo                                     ENDP
D3DKMTSetDisplayPrivateDriverFormat                        PROC
    JUMP 8
D3DKMTSetDisplayPrivateDriverFormat                        ENDP
D3DKMTSignalSynchronizationObject                          PROC
    JUMP 9
D3DKMTSignalSynchronizationObject                          ENDP
D3DKMTUnlock                                               PROC
    JUMP 10
D3DKMTUnlock                                               ENDP
D3DKMTWaitForSynchronizationObject                         PROC
    JUMP 11
D3DKMTWaitForSynchronizationObject                         ENDP
EnableFeatureLevelUpgrade                                  PROC
    JUMP 12
EnableFeatureLevelUpgrade                                  ENDP
OpenAdapter10                                              PROC
    JUMP 13
OpenAdapter10                                              ENDP
OpenAdapter10_2                                            PROC
    JUMP 14
OpenAdapter10_2                                            ENDP
CreateDirect3D11DeviceFromDXGIDevice                       PROC
    JUMP 15
CreateDirect3D11DeviceFromDXGIDevice                       ENDP
CreateDirect3D11SurfaceFromDXGISurface                     PROC
    JUMP 16
CreateDirect3D11SurfaceFromDXGISurface                     ENDP
D3D11CoreCreateDevice                                      PROC
    JUMP 17
D3D11CoreCreateDevice                                      ENDP
D3D11CoreCreateLayeredDevice                               PROC
    JUMP 18
D3D11CoreCreateLayeredDevice                               ENDP
D3D11CoreGetLayeredDeviceSize                              PROC
    JUMP 19
D3D11CoreGetLayeredDeviceSize                              ENDP
D3D11CoreRegisterLayers                                    PROC
    JUMP 20
D3D11CoreRegisterLayers                                    ENDP
D3D11CreateDevice                                          PROC
    JUMP 21
D3D11CreateDevice                                          ENDP
D3D11CreateDeviceAndSwapChain                              PROC
    JUMP 22
D3D11CreateDeviceAndSwapChain                              ENDP
D3D11On12CreateDevice                                      PROC
    JUMP 23
D3D11On12CreateDevice                                      ENDP
D3DKMTCreateAllocation                                     PROC
    JUMP 24
D3DKMTCreateAllocation                                     ENDP
D3DKMTCreateContext                                        PROC
    JUMP 25
D3DKMTCreateContext                                        ENDP
D3DKMTCreateDevice                                         PROC
    JUMP 26
D3DKMTCreateDevice                                         ENDP
D3DKMTCreateSynchronizationObject                          PROC
    JUMP 27
D3DKMTCreateSynchronizationObject                          ENDP
D3DKMTEscape                                               PROC
    JUMP 28
D3DKMTEscape                                               ENDP
D3DKMTGetContextSchedulingPriority                         PROC
    JUMP 29
D3DKMTGetContextSchedulingPriority                         ENDP
D3DKMTGetDeviceState                                       PROC
    JUMP 30
D3DKMTGetDeviceState                                       ENDP
D3DKMTGetDisplayModeList                                   PROC
    JUMP 31
D3DKMTGetDisplayModeList                                   ENDP
D3DKMTGetMultisampleMethodList                             PROC
    JUMP 32
D3DKMTGetMultisampleMethodList                             ENDP
D3DKMTGetRuntimeData                                       PROC
    JUMP 33
D3DKMTGetRuntimeData                                       ENDP
D3DKMTGetSharedPrimaryHandle                               PROC
    JUMP 34
D3DKMTGetSharedPrimaryHandle                               ENDP
D3DKMTLock                                                 PROC
    JUMP 35
D3DKMTLock                                                 ENDP
D3DKMTOpenAdapterFromHdc                                   PROC
    JUMP 36
D3DKMTOpenAdapterFromHdc                                   ENDP
D3DKMTOpenResource                                         PROC
    JUMP 37
D3DKMTOpenResource                                         ENDP
D3DKMTQueryAllocationResidency                             PROC
    JUMP 38
D3DKMTQueryAllocationResidency                             ENDP
D3DKMTQueryResourceInfo                                    PROC
    JUMP 39
D3DKMTQueryResourceInfo                                    ENDP
D3DKMTRender                                               PROC
    JUMP 40
D3DKMTRender                                               ENDP
D3DKMTSetAllocationPriority                                PROC
    JUMP 41
D3DKMTSetAllocationPriority                                ENDP
D3DKMTSetContextSchedulingPriority                         PROC
    JUMP 42
D3DKMTSetContextSchedulingPriority                         ENDP
D3DKMTSetDisplayMode                                       PROC
    JUMP 43
D3DKMTSetDisplayMode                                       ENDP
D3DKMTSetGammaRamp                                         PROC
    JUMP 44
D3DKMTSetGammaRamp                                         ENDP
D3DKMTSetVidPnSourceOwner                                  PROC
    JUMP 45
D3DKMTSetVidPnSourceOwner                                  ENDP
D3DKMTWaitForVerticalBlankEvent                            PROC
    JUMP 46
D3DKMTWaitForVerticalBlankEvent                            ENDP
D3DPerformance_BeginEvent                                  PROC
    JUMP 47
D3DPerformance_BeginEvent                                  ENDP
D3DPerformance_EndEvent                                    PROC
    JUMP 48
D3DPerformance_EndEvent                                    ENDP
D3DPerformance_GetStatus                                   PROC
    JUMP 49
D3DPerformance_GetStatus                                   ENDP
D3DPerformance_SetMarker                                   PROC
    JUMP 50
D3DPerformance_SetMarker                                   ENDP
END
