; Proxy shell trampolines (#83, ml64) - GENERATED by scripts/gen_shell_asm.py.
; Export table source: link /dump /exports System32\d3d12.dll (via
; src/shell/shell_exports.h, SHELL_ID=1). Ordinals are the REAL dll's
; ordinals - games import by ordinal via the .lib (d3d12.lib maps
; D3D12CreateDevice to ordinal 101), so the table must match exactly.
; Each slot: save volatile arg registers -> first entry calls ProxyBootstrap
; (guarded by g_inited; steady state is cmp+jne only) -> restore -> jmp to
; the real dll's same slot (by name; unnamed slots by ordinal). Signature-
; agnostic: stack args stay in place, register args are saved/restored.
option casemap:none

extern g_procs:qword
extern g_inited:byte
extern ProxyBootstrap:proc

.code

JUMP MACRO idx
    sub     rsp, 104
    movaps  [rsp+0], xmm3
    mov     [rsp+16], rcx
    mov     [rsp+24], rdx
    mov     [rsp+32], r8
    mov     [rsp+40], r9
    movaps  [rsp+48], xmm0
    movaps  [rsp+64], xmm1
    movaps  [rsp+80], xmm2
    cmp     byte ptr [g_inited], 0
    jne     SHORT skip_init&idx&
    call    ProxyBootstrap
skip_init&idx&:
    movaps  xmm3, [rsp+0]
    mov     rcx, [rsp+16]
    mov     rdx, [rsp+24]
    mov     r8,  [rsp+32]
    mov     r9,  [rsp+40]
    movaps  xmm0, [rsp+48]
    movaps  xmm1, [rsp+64]
    movaps  xmm2, [rsp+80]
    add     rsp, 104
    jmp     qword ptr [g_procs+idx*8]
ENDM

OrdinalSlot_99                                             PROC
    JUMP 0
OrdinalSlot_99                                             ENDP
GetBehaviorValue                                           PROC
    JUMP 1
GetBehaviorValue                                           ENDP
D3D12CreateDevice                                          PROC
    JUMP 2
D3D12CreateDevice                                          ENDP
D3D12GetDebugInterface                                     PROC
    JUMP 3
D3D12GetDebugInterface                                     ENDP
SetAppCompatStringPointer                                  PROC
    JUMP 4
SetAppCompatStringPointer                                  ENDP
D3D12CoreCreateLayeredDevice                               PROC
    JUMP 5
D3D12CoreCreateLayeredDevice                               ENDP
D3D12CoreGetLayeredDeviceSize                              PROC
    JUMP 6
D3D12CoreGetLayeredDeviceSize                              ENDP
D3D12CoreRegisterLayers                                    PROC
    JUMP 7
D3D12CoreRegisterLayers                                    ENDP
D3D12CreateRootSignatureDeserializer                       PROC
    JUMP 8
D3D12CreateRootSignatureDeserializer                       ENDP
D3D12CreateVersionedRootSignatureDeserializer              PROC
    JUMP 9
D3D12CreateVersionedRootSignatureDeserializer              ENDP
D3D12DeviceRemovedExtendedData                             PROC
    JUMP 10
D3D12DeviceRemovedExtendedData                             ENDP
D3D12EnableExperimentalFeatures                            PROC
    JUMP 11
D3D12EnableExperimentalFeatures                            ENDP
D3D12GetInterface                                          PROC
    JUMP 12
D3D12GetInterface                                          ENDP
D3D12PIXEventsReplaceBlock                                 PROC
    JUMP 13
D3D12PIXEventsReplaceBlock                                 ENDP
D3D12PIXGetThreadInfo                                      PROC
    JUMP 14
D3D12PIXGetThreadInfo                                      ENDP
D3D12PIXNotifyWakeFromFenceSignal                          PROC
    JUMP 15
D3D12PIXNotifyWakeFromFenceSignal                          ENDP
D3D12PIXReportCounter                                      PROC
    JUMP 16
D3D12PIXReportCounter                                      ENDP
D3D12SerializeRootSignature                                PROC
    JUMP 17
D3D12SerializeRootSignature                                ENDP
D3D12SerializeVersionedRootSignature                       PROC
    JUMP 18
D3D12SerializeVersionedRootSignature                       ENDP
END
