; Proxy shell trampolines (#83, ml64) - GENERATED by scripts/gen_shell_asm.py.
; Export table source: link /dump /exports System32\dxgi.dll (via
; src/shell/shell_exports.h, SHELL_ID=4). Ordinals are the REAL dll's
; ordinals - games import by ordinal via the .lib (d3d12.lib maps
; D3D12CreateDevice to ordinal 101), so the table must match exactly.
; Each slot: save volatile arg registers -> first entry calls ProxyBootstrap
; (guarded by g_inited; steady state is cmp+jne only) -> restore -> jmp to
; the real dll's same slot (by name; unnamed slots by ordinal). Signature-
; agnostic: stack args stay in place, register args are saved/restored.
option casemap:none

extern g_procs:qword
extern g_inited:byte
extern ProxyBootstrap:proc

.code

JUMP MACRO idx
    sub     rsp, 104
    movaps  [rsp+0], xmm3
    mov     [rsp+16], rcx
    mov     [rsp+24], rdx
    mov     [rsp+32], r8
    mov     [rsp+40], r9
    movaps  [rsp+48], xmm0
    movaps  [rsp+64], xmm1
    movaps  [rsp+80], xmm2
    cmp     byte ptr [g_inited], 0
    jne     SHORT skip_init&idx&
    call    ProxyBootstrap
skip_init&idx&:
    movaps  xmm3, [rsp+0]
    mov     rcx, [rsp+16]
    mov     rdx, [rsp+24]
    mov     r8,  [rsp+32]
    mov     r9,  [rsp+40]
    movaps  xmm0, [rsp+48]
    movaps  xmm1, [rsp+64]
    movaps  xmm2, [rsp+80]
    add     rsp, 104
    jmp     qword ptr [g_procs+idx*8]
ENDM

ApplyCompatResolutionQuirking                              PROC
    JUMP 0
ApplyCompatResolutionQuirking                              ENDP
CompatString                                               PROC
    JUMP 1
CompatString                                               ENDP
CompatValue                                                PROC
    JUMP 2
CompatValue                                                ENDP
DXGIDumpJournal                                            PROC
    JUMP 3
DXGIDumpJournal                                            ENDP
PIXBeginCapture                                            PROC
    JUMP 4
PIXBeginCapture                                            ENDP
PIXEndCapture                                              PROC
    JUMP 5
PIXEndCapture                                              ENDP
PIXGetCaptureState                                         PROC
    JUMP 6
PIXGetCaptureState                                         ENDP
SetAppCompatStringPointer                                  PROC
    JUMP 7
SetAppCompatStringPointer                                  ENDP
UpdateHMDEmulationStatus                                   PROC
    JUMP 8
UpdateHMDEmulationStatus                                   ENDP
CreateDXGIFactory                                          PROC
    JUMP 9
CreateDXGIFactory                                          ENDP
CreateDXGIFactory1                                         PROC
    JUMP 10
CreateDXGIFactory1                                         ENDP
CreateDXGIFactory2                                         PROC
    JUMP 11
CreateDXGIFactory2                                         ENDP
DXGID3D10CreateDevice                                      PROC
    JUMP 12
DXGID3D10CreateDevice                                      ENDP
DXGID3D10CreateLayeredDevice                               PROC
    JUMP 13
DXGID3D10CreateLayeredDevice                               ENDP
DXGID3D10GetLayeredDeviceSize                              PROC
    JUMP 14
DXGID3D10GetLayeredDeviceSize                              ENDP
DXGID3D10RegisterLayers                                    PROC
    JUMP 15
DXGID3D10RegisterLayers                                    ENDP
DXGIDeclareAdapterRemovalSupport                           PROC
    JUMP 16
DXGIDeclareAdapterRemovalSupport                           ENDP
DXGIGetDebugInterface1                                     PROC
    JUMP 17
DXGIGetDebugInterface1                                     ENDP
DXGIReportAdapterConfiguration                             PROC
    JUMP 18
DXGIReportAdapterConfiguration                             ENDP
END
