$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'paths.ps1')
Set-Location $SourceRoot
$kit = Get-ChildItem -LiteralPath (Join-Path ${env:ProgramFiles(x86)} 'Windows Kits/10/bin') -Directory | Sort-Object Name -Descending | Where-Object { (Test-Path -LiteralPath (Join-Path $_.FullName 'x64/dxc.exe')) -and (Test-Path -LiteralPath (Join-Path $_.FullName 'x64/fxc.exe')) } | Select-Object -First 1
if (!$kit) { throw 'Install Windows SDK with dxc.exe and fxc.exe.' }
$dxc = Join-Path $kit.FullName 'x64/dxc.exe'
$fxc = Join-Path $kit.FullName 'x64/fxc.exe'
$sdk = 'third_party/fidelityfx/sdk'
$generated = 'src/core/shaders/precompiled/optical'
$output = Resolve-DxlOutput '' 'optical-shaders'
New-Item -ItemType Directory -Path $generated,$output -Force | Out-Null
$passes = @('prepare_luma','compute_luminance_pyramid','generate_scd_histogram','compute_scd_divergence','compute_optical_flow_advanced','filter_optical_flow','scale_optical_flow_advanced')
$metadata = [Text.StringBuilder]::new()
[void]$metadata.AppendLine('// Generated by scripts/build_optical_shaders.ps1 from AMD FidelityFX 1.1.4 (MIT).')
$initializers = @()
for ($index = 0; $index -lt $passes.Count; ++$index) {
    $name = 'ffx_opticalflow_' + $passes[$index] + '_pass'
    if ($index -ge 4) { $name += '_v5' }
    $assembly = (Join-Path $output "$name.asm")
    & $dxc -E CS -T cs_6_2 -O3 -D FFX_GPU=1 -D FFX_HLSL=1 -D FFX_HLSL_SM=62 -D FFX_HALF=0 -D FFX_OPTICALFLOW_OPTION_HDR_COLOR_INPUT=0 -I "$sdk/include/FidelityFX/gpu" -Fo (Join-Path $output "$name.dxil") -Fc $assembly -Fh "$generated/Pass$index.h" -Vn "kOpticalPass$index" "$sdk/src/backends/dx12/shaders/opticalflow/$name.hlsl"
    if ($LASTEXITCODE) { throw "Optical shader failed: $name" }
    [void]$metadata.AppendLine("#include `"Pass$index.h`"")
    $groups = @(@(),@(),@(),@(),@(),@(),@())
    $inside = $false
    foreach ($line in (Get-Content -LiteralPath $assembly)) {
        if ($line -eq '; Resource Bindings:') { $inside = $true; continue }
        if (!$inside) { continue }
        if ($line -match '^;\s+(\w+)\s+(\w+)\s+(\S+)\s+(\S+)\s+(?:\w+)\s+(cb|t|u|s)(\d+)(?:,space(\d+))?\s+(\d+)\s*$') {
            $resourceName=$matches[1]; $dimension=$matches[4]; $kind=$matches[5]; $slot=$matches[6]; $space=if ($matches[7]) {$matches[7]} else {'0'}; $count=$matches[8]
            $group = switch ($kind) { 'cb' {0}; 't' {if ($dimension -eq '2d' -or $dimension -eq '1d') {1} else {3}}; 'u' {if ($dimension -eq '2d' -or $dimension -eq '1d') {2} else {4}}; 's' {5} }
            $groups[$group] += [pscustomobject]@{Name=$resourceName; Slot=$slot; Count=$count; Space=$space}
        } elseif ($line -eq ';' -and (($groups | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum -gt 0)) { break }
    }
    if (!(($groups | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum)) { throw "No reflection bindings for $name" }
    $counts=@(); $pointers=@()
    for ($group=0; $group -lt 7; ++$group) {
        $items=$groups[$group]; $counts += $items.Count
        if (!$items.Count) { $pointers += 'nullptr, nullptr, nullptr, nullptr'; continue }
        $symbol="kP${index}R${group}"
        $names=($items | ForEach-Object {'"'+$_.Name+'"'}) -join ','
        [void]$metadata.AppendLine("static const char* ${symbol}Names[] = {$names};")
        foreach ($column in @('Slot','Count','Space')) {
            $values=($items | ForEach-Object { $_.$column }) -join ','
            [void]$metadata.AppendLine("static const uint32_t $symbol$column`[] = {$values};")
        }
        $pointers += "${symbol}Names, ${symbol}Slot, ${symbol}Count, ${symbol}Space"
    }
    $initializers += '{ kOpticalPass' + $index + ', sizeof(kOpticalPass' + $index + '), ' + ($counts -join ', ') + ', ' + ($pointers -join ', ') + ' }'
}
[void]$metadata.AppendLine('static const FfxShaderBlob kOpticalBlobs[] = {' + ($initializers -join ",`n") + '};')
[IO.File]::WriteAllText((Join-Path (Get-Location) "$generated/Blobs.h"), $metadata.ToString(), [Text.UTF8Encoding]::new($false))
'Optical shaders compiled: seven FP32 / wave32-compatible DXIL kernels; no runtime compiler needed.'
& $fxc /nologo /T cs_5_0 /E Main /O3 /Fh src/core/shaders/precompiled/OpticalDensify.h /Vn kOpticalDensify src/core/shaders/OpticalDensify.hlsl
if ($LASTEXITCODE) { throw 'Densification shader failed' }
