# 代理壳生成器 v2（#83）：System32 dump -> shell_exports.h + shell_<n>.asm/.def。
#
# v1 只按名导出 —— v2 起按序号忠实复刻真 DLL 的导出表：
#   · 游戏（经 .lib）常按**序号**导入（d3d12.lib 的 D3D12CreateDevice -> #101），
#     按名的壳对不上序号 -> 加载器解析导入失败 -> 进程无输出秒死（冒烟抓的）。
#   · 真 DLL 还有未命名导出（d3d12 #99、xinput 一大串）：按序号槽位转发
#     （GetProcAddress(MAKEINTRESOURCE(ord))）。
#   · xinput 的 "DllMain"（@1）是加载器内部通道，不代理名 —— 按序号槽位处理。
#
# 单一数据源：本机 link /dump /exports 的输出（DXL_WORKSPACE/diagnostics/shellgen/<n>.txt，
# `link /dump /exports C:\Windows\System32\<n>.dll` 重新生成）。
# Windows 更新后重跑本脚本即可换表；产物（头/asm/def）入库可审。
# 三处由同一张表派生，不可能漂移：kShellExports[]（C++，按序号升序）
# == asm 跳板序 == .def 导出序。
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORKSPACE = Path(os.environ.get("DXL_WORKSPACE", ROOT.parent / "DXL-Workspace")).resolve()
if WORKSPACE == ROOT or ROOT in WORKSPACE.parents:
    raise SystemExit("DXL_WORKSPACE must be outside source.")
DUMPS = WORKSPACE / "diagnostics" / "shellgen"
SHELLS = {1: "d3d12", 2: "d3d11", 3: "xinput1_4", 4: "dxgi"}
# 不代理名的导出（按序号槽位转发）：xinput DllMain 是加载器内部通道。
SKIP_NAMES = {"xinput1_4": {"DllMain"}}

ASM_TEMPLATE = """; Proxy shell trampolines (#83, ml64) - GENERATED by scripts/gen_shell_asm.py.
; Export table source: link /dump /exports System32\\{name}.dll (via
; src/shell/shell_exports.h, SHELL_ID={sid}). Ordinals are the REAL dll's
; ordinals - games import by ordinal via the .lib (d3d12.lib maps
; D3D12CreateDevice to ordinal 101), so the table must match exactly.
; Each slot: save volatile arg registers -> first entry calls ProxyBootstrap
; (guarded by g_inited; steady state is cmp+jne only) -> restore -> jmp to
; the real dll's same slot (by name; unnamed slots by ordinal). Signature-
; agnostic: stack args stay in place, register args are saved/restored.
option casemap:none

extern g_procs:qword
extern g_inited:byte
extern ProxyBootstrap:proc

.code

JUMP MACRO idx
    sub     rsp, 104
    movaps  [rsp+0], xmm3
    mov     [rsp+16], rcx
    mov     [rsp+24], rdx
    mov     [rsp+32], r8
    mov     [rsp+40], r9
    movaps  [rsp+48], xmm0
    movaps  [rsp+64], xmm1
    movaps  [rsp+80], xmm2
    cmp     byte ptr [g_inited], 0
    jne     SHORT skip_init&idx&
    call    ProxyBootstrap
skip_init&idx&:
    movaps  xmm3, [rsp+0]
    mov     rcx, [rsp+16]
    mov     rdx, [rsp+24]
    mov     r8,  [rsp+32]
    mov     r9,  [rsp+40]
    movaps  xmm0, [rsp+48]
    movaps  xmm1, [rsp+64]
    movaps  xmm2, [rsp+80]
    add     rsp, 104
    jmp     qword ptr [g_procs+idx*8]
ENDM

{procs}
END
"""


def parse_dump(path: Path):
    text = path.read_text(errors="replace")
    base = int(re.search(r"(\d+) ordinal base", text).group(1))
    nfun = int(re.search(r"(\d+) number of functions", text).group(1))
    nnam = int(re.search(r"(\d+) number of names", text).group(1))
    named = {}
    m = re.search(r"ordinal hint RVA\s+name\s*\n(.*?)\n\s*\n", text, re.S)
    for line in m.group(1).splitlines():
        mm = re.match(r"\s*(\d+)\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+(\S+)", line)
        if mm:
            named[int(mm.group(1))] = mm.group(2)
    assert len(named) == nnam, f"{path.name}: names {len(named)} != header {nnam}"
    slots = []          # (ordinal, name-or-None) 按序号升序
    for ordinal in range(base, base + nfun):
        name = named.get(ordinal)
        if name in SKIP_NAMES.get(path.stem, {}):
            name = None
        slots.append((ordinal, name))
    assert len(slots) == nfun
    return slots


def slot_symbol(ordinal, name):
    return name if name else f"OrdinalSlot_{ordinal}"


def main():
    header = ["// 代理壳导出表（#83）—— scripts/gen_shell_asm.py 生成，别手改。",
              "// 单一数据源：link /dump /exports System32\\<dll>（build\\shellgen\\*.txt）。",
              "// Windows 更新导出面后重跑生成器换表。",
              "//",
              "// **序号 = 真 DLL 的序号，必须逐一对上**：游戏经 .lib 常按序号导入",
              "//（d3d12.lib 把 D3D12CreateDevice 映到 #101）—— 按名的壳对不上序号，",
              "// 加载器解析导入失败，进程无输出秒死（v1 冒烟抓的）。",
              "// name=nullptr 是未命名槽位（d3d12 #99、xinput 一大串）：按序号转发，",
              "// GetProcAddress(MAKEINTRESOURCE(ordinal))。xinput 的 DllMain@1",
              "// 不代理名（加载器内部通道，不是 API），也走序号槽位。",
              "#pragma once",
              "",
              "#include <cstdint>",
              "",
              "namespace d5q {",
              "",
              "struct ShellExport {",
              "    uint16_t ordinal;      // 真 DLL 的绝对序号",
              "    const char* name;     // nullptr = 未命名槽位（按序号转发）",
              "};",
              ""]
    for sid, name in SHELLS.items():
        slots = parse_dump(DUMPS / f"{name}.txt")
        header.append(f"// ---- SHELL_ID={sid}: {name}（{len(slots)} 槽位）----")
        header.append(f"inline constexpr ShellExport kShellExports{sid}[] = {{")
        for ordinal, nm in slots:
            # 无名槽位写 nullptr —— repr(None) 是 Python 的 None，C++ 编译不过
            value = "nullptr" if nm is None else f'"{nm}"'
            header.append(f"    {{{ordinal}, {value}}},")
        header.append("};")
        header.append(f"static_assert(sizeof(kShellExports{sid}) / sizeof(ShellExport)"
                      f" == {len(slots)}, \"slot count\");")
        header.append("")
    header.append("}  // namespace d5q")
    (ROOT / "src" / "shell" / "shell_exports.h").write_text(
        "\n".join(header) + "\n", encoding="utf-8", newline="\r\n")

    for sid, name in SHELLS.items():
        slots = parse_dump(DUMPS / f"{name}.txt")
        procs = "\n".join(
            f"{slot_symbol(o, nm):<58} PROC\n    JUMP {i}\n"
            f"{slot_symbol(o, nm):<58} ENDP"
            for i, (o, nm) in enumerate(slots))
        (ROOT / "src" / "shell" / f"shell_{name}.asm").write_text(
            ASM_TEMPLATE.format(sid=sid, name=name, procs=procs),
            encoding="ascii", newline="\r\n")
        # marker 序号：d3d12 塞 base 之下的死区（@1，真表 99 起）；其余 max+1。
        # d3d12 会一直往上加导出，max+1 会撞未来的新导出；d3d11/dxgi/xinput
        # 的表十年没动过，max+1 够安全。
        maxord = max(o for o, _ in slots)
        marker_ord = 1 if name == "d3d12" else maxord + 1
        deff = ["LIBRARY", "EXPORTS"]
        deff += [f"    {slot_symbol(o, nm)} @{o}" for o, nm in slots]
        deff.append(f"    D5QShellMarker @{marker_ord}")
        (ROOT / "src" / "shell" / f"shell_{name}.def").write_text(
            "\n".join(deff) + "\n", encoding="ascii", newline="\r\n")
        unnamed = sum(1 for _, nm in slots if not nm)
        print(f"SHELL_ID={sid} {name}: {len(slots)} slots"
              f"（{len(slots) - unnamed} named + {unnamed} ordinal-only）"
              f", marker @{marker_ord}")


if __name__ == "__main__":
    main()
